name: jsfaker Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    container: node:latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm install -g typescript
      - run: tsc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PERSONAL_TOKEN}}
